name          'garethr-tasseo'
version       '0.0.1'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to manage the Tasseo graphite dashboard'
project_page  'https://github.com/garethr/garethr-tasseo'
dependency    'puppetlabs/vcsrepo'
